In [1]:
import pandas as pd

totalData = None

for i in range(1987, 2013):
    data = pd.read_csv("./trainData/"+ str(i+1) + "mvpVotes.csv")
    if(i == 1987):
        totalData = pd.DataFrame(columns = data.columns)
    totalData = pd.concat([totalData, data], ignore_index=True)

for column in data.columns:
    totalData.rename(columns={column:data.loc[0].at[column]}, inplace=True)

totalData = totalData.drop(totalData.index[0])
totalData = totalData.drop(totalData.columns[[0]], axis=1)
totalData['3P%'] = totalData['3P%'].fillna(0)
display(totalData)
totalData.info()

/var/folders/wt/9zq91pyx6_v1y0834wk75jgc0000gn/T/ipykernel_71194/3934704965.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  totalData = pd.concat([totalData, data], ignore_index=True)

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
1,1,Michael Jordan,24,CHI,47,665,800,0.831,82,40.4,35.0,5.5,5.9,3.2,1.6,0.535,0.132,0.841,21.2,0.308
2,2,Larry Bird,31,BOS,16,527,800,0.659,76,39.0,29.9,9.3,6.1,1.6,0.8,0.527,0.414,0.916,15.0,0.243
3,3,Magic Johnson,28,LAL,16,508,800,0.635,72,36.6,19.6,6.2,11.9,1.6,0.2,0.492,0.196,0.853,10.9,0.199
4,4,Charles Barkley,24,PHI,1,109,800,0.136,80,39.6,28.3,11.9,3.2,1.3,1.3,0.587,0.28,0.751,16.7,0.253
5,5,Clyde Drexler,25,POR,0,86,800,0.108,81,37.8,27.0,6.6,5.8,2.5,0.6,0.506,0.212,0.811,13.2,0.207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,12T,Kevin Garnett,36,BOS,0,1,1210,0.001,68,29.7,14.8,7.8,2.3,1.1,0.9,0.496,0.125,0.786,5.6,0.133
444,12T,Marc Gasol,28,MEM,0,1,1210,0.001,80,35.0,14.1,7.8,4.0,1.0,1.7,0.494,0.071,0.848,11.5,0.197
445,12T,Ty Lawson,25,DEN,0,1,1210,0.001,73,34.4,16.7,2.7,6.9,1.5,0.1,0.461,0.366,0.756,7.4,0.141
446,12T,David Lee,29,GSW,0,1,1210,0.001,79,36.8,18.5,11.2,3.5,0.8,0.3,0.519,0.0,0.797,9.1,0.15
447,12T,Joakim Noah,27,CHI,0,1,1210,0.001,66,36.8,11.9,11.1,4.0,1.2,2.1,0.481,0.0,0.751,7.3,0.145

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 447 entries, 1 to 447
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     447 non-null    object
 1   Player   447 non-null    object
 2   Age      447 non-null    object
 3   Tm       447 non-null    object
 4   First    447 non-null    object
 5   Pts Won  447 non-null    object
 6   Pts Max  447 non-null    object
 7   Share    447 non-null    object
 8   G        447 non-null    object
 9   MP       447 non-null    object
 10  PTS      447 non-null    object
 11  TRB      447 non-null    object
 12  AST      447 non-null    object
 13  STL      447 non-null    object
 14  BLK      447 non-null    object
 15  FG%      447 non-null    object
 16  3P%      447 non-null    object
 17  FT%      447 non-null    object
 18  WS       447 non-null    object
 19  WS/48    447 non-null    object
dtypes: object(20)
memory usage: 70.0+ KB